
*Tag:* configurations *Parent:* link:../ivyfile.html[ivy-module]

A container for configuration elements. If this container is not present, it is assumed that the module has one public configuration called 'default'.

*__since 2.2__* You can define the default conf on this container by specifying the defaultconf attribute.  This attribute defines the conf mapping to use when no conf mapping is specified for a dependency in this ivy file.

*__since 1.3__* You can define a default conf mapping on this container by specifying the defaultconfmapping attribute.

This attribute modifies the way ivy interprets conf mapping with no mapped conf. In this case, Ivy will look in the default conf mapping and use the conf mapping defined in the default conf mapping for the conf for which there is no mapped conf.

In order to maintain backwards compatibility with Ivy 2.1.0 and earlier, the defaultconfmapping also provides one additional function.  If no defaultconf is specified (on either the configurations tag or the dependencies tag), the defaultconfmapping becomes the default configuration for dependencies in this ivy file when no configuration is specified.  In other words, in addition to altering the interpretation of individual configurations with no mapping, defaultconfmapping also performs exactly like defaultconf in the absence of a definition for defaultconf.

If several defaultconfmapping or defaultconf attributes are defined (in the configurations tag, one or several in an included configurations file, and/or in the dependency tag, then it's only the last definition of each property which is taken into account.  The others will have no effect at all.

See link:#defaultconfmapping[examples below] to clarify the behavior of these two attributes together.

*__since 1.4__* You can activate a confmappingoverride mode for all configurations, in which case the extending configurations will override the mappings of the configurations they extend from.



== Attributes


[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|defaultconf|the default conf to use in this ivy file *__since 2.2__*|No, defaults to no default conf
|defaultconfmapping|the default conf mapping to use in this ivy file *__since 1.3__*|No, defaults to no default conf mapping
|confmappingoverride|true to activate configuration mapping override, false otherwise *__since 1.4__*|No, defaults to false
|=======


== Child elements


[options="header"]
|=======
|Element|Description|Cardinality
|link:../ivyfile/conf.html[conf]|declares a configuration of this module|0..n
|link:../ivyfile/include.html[include]|include configurations from another file|0..n
|=======



== Configuration mappings details

When Ivy parses your Ivy file, it will create (internally) modify the configuration mapping of your dependencies.
For instance, say you have:

[source]
----

<configurations defaultconfmapping="conf1->other1;conf2->other2">
   <conf name="conf1" />
   <conf name="conf2" extends="conf1" />
</configurations>
<dependencies>
   <dependency name="other-module" conf="conf1" />
</dependencies>

----

When Ivy parses this file, it will construct the following dependency (in-memory only):

[source]
----
<dependency name="other-module" conf="conf1->other1" />
----

So, if you now resolve the conf2 configuration, you will only get the other1 dependencies of your other-module.

But when you set confmappingoverride to true, Ivy will construct the following dependency in memory:

[source]
----
<dependency name="other-module" conf="conf1->other1;conf2->other2" />
----

As you can see, the defaultmappings of the extending configurations are also added (although you didn't explicitly defined them)

When you now resolve the conf2 configuration, you'll get the other2 dependencies of your other-module. 


== Examples involving defaultconf and defaultconfmapping

The table below indicates how Ivy interprets the conf attribute according to how link:../ivyfile/configurations.html[defaultconfmapping] and link:../ivyfile/configurations.html[defaultconf] are set:
[options="header",cols="15%,50%,18%,18%"]
|=======
|defaultconf|defaultconfmapping|conf|ivy interpretation
||||
[source]
----
*->*
----


|||runtime|
[source]
----
runtime->runtime
----


|||test|
[source]
----
test->test
----


|
[source]
----
runtime
----

|||
[source]
----
runtime->runtime
----


|
[source]
----
runtime
----

|
[source]
----
runtime->*;test->default
----

||runtime->*
|
[source]
----
runtime
----

|
[source]
----
runtime->*;test->default
----

|test|test->default
||
[source]
----
runtime->*;test->default
----

||
[source]
----
runtime->*;test->default
----


||
[source]
----
runtime->*;test->default
----

|runtime|
[source]
----
runtime->*
----


||
[source]
----
runtime->*;test->default
----

|test|
[source]
----
test->default
----


|=======
