////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

*Tag:* dependencies *Parent:* link:../ivyfile.html[ivy-module]

Container for dependency elements, used to describe the dependencies of this module.
If this container is not present, it is assumed that the module has no dependency at all.

This container provides two similar behaviors described below. (See link:../ivyfile/configurations.html[configurations doc page] for more details about these behaviors).

(*__since 1.1__*) `defaultconf` defines the `conf` attribute to use when no conf is defined for a dependency in this Ivy file. It is only used when no conf mapping is defined, and has no influence in other cases.

(*__since 1.3__*) `defaultconfmapping` influences the way that a conf mapping with no mapped conf is interpreted.

In Ivy 2.1.0 and earlier, if both `defaultconf` and `defaultconfmapping` are defined, it's the `defaultconfmapping` that is used. Since Ivy 2.2.0, these attributes can be used together.

== Attributes

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|defaultconf|the default configuration to use when none is specified in a dependency. (*__since 1.1__*)|No, defaults to `$$*->*$$`
|defaultconfmapping|the default configuration mapping to use in this Ivy file. (*__since 1.3__*)|No, defaults to no default conf mapping
|=======


== Child elements


Note: as specified by the ivy.xsd, the children elements are ordered; first must come the `link:../ivyfile/dependency.html[dependency]` elements, then the `link:../ivyfile/exclude.html[exclude]` elements, then the `link:../ivyfile/override.html[override]` elements, and then the `link:../ivyfile/conflict.html[conflict]` elements.


[options="header",cols="20%,60%,20%"]
|=======
|Element|Description|Cardinality
|link:../ivyfile/dependency.html[dependency]|declares a dependency for this module|0..n
|link:../ivyfile/exclude.html[exclude]|excludes artifacts, modules or whole organizations from the set of dependencies of this module (*__since 2.0__*)|0..n
|link:../ivyfile/override.html[override]|specifies an override mediation rule, overriding the revision and/or branch requested for a transitive dependency (*__since 2.0__*)|0..n
|link:../ivyfile/conflict.html[conflict]|specifies a conflict manager for one or several dependencies (*__since 2.0__*)|0..n
|=======
