////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

*Tag:* exclude *Parent:* link:../ivyfile/dependencies{outfilesuffix}[dependencies]

[*__since 2.0__*]

This feature gives you more control on a dependency for which you do not control its Ivy file.
It allows to exclude artifacts, modules or organizations from the list of dependencies for the whole module.

It is very similar to the link:../ivyfile/artifact-exclude.html[dependency exclude] element, except that it applies to a whole module, which can be very useful when a lot of dependencies transitively bring a module you don't want.

== Attributes

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|org|the organization of the dependency module or artifact to exclude, or a regexp matching this organization|No, defaults to `$$*$$`
|module|the name of the dependency module or the artifact to exclude, or a regexp matching this module name|No, defaults to `$$*$$`
|artifact|the name of an artifact of the dependency module to add to the exclude list, or an expression matching this name (see `matcher` attribute below)|No, defaults to `$$*$$`
|type|the type of the artifact of the dependency module to add to the exclude list, or a regexp matching this name|No, defaults to `$$*$$`
|ext|the extension of the artifact of the dependency module to add to the exclude list, or an expression matching this name (see `matcher` attribute below)|No, defaults to the value of `type`
|matcher|the link:../concept{outfilesuffix}#matcher[matcher] to use to match the modules to excludes|No, defaults to `exactOrRegexp` in pre 1.3 Ivy files, and `exact` in 1.3 and superior
|conf|comma separated list of the master configurations in which this artifact should be included.

`$$*$$` wildcard can be used to designate all configurations of this module|No, defaults to `$$*$$`, unless nested conf are specified
|=======
