////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

*Tag:* manager *Parent:* link:../ivyfile/conflicts.html[conflicts]

*__(since 2.0)__* the conflicts section is deprecated.  Use the link:../ivyfile/conflict.html[conflict] instead.

Specify a a conflict manager for one or several dependencies.

The way to specify a conflict manager is by giving indication to which dependencies the conflict manager applies (by giving organisation and module names or name regexp), and then specifying the conflict manager, either by giving its name or by specifying a fixed revision list, in which case a fixed conflicts manager is used.

See link:../ivyfile/conflicts.html[Conflicts Manager] for details on conflicts manager in general.

== Attributes

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|org|the name, or an expression matching the name of organisation to which this conflict manager should apply (see `matcher` attribute below)|No, defaults to `$$*$$` (match all)
|module|the name, or an expression matching the name of module to which this conflict manager should apply (see `matcher` attribute below)|No, defaults to `$$*$$` (match all)
|name|the name of the conflict manager to use
.2+.^|Exactly one of two
|rev|a comma separated list of revisions this conflict manager should select
|matcher|the link:../concept.html#matcher[matcher] to use to match the modules for which the conflict manager should be used *__since 1.3__*|No, defaults to `exactOrRegexp` in pre 1.3 ivy files, and `exact` in 1.3 and superior
|=======
