////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

*Tag:* publications *Parent:* link:../ivyfile{outfilesuffix}[ivy-module]

Container for `artifact` elements, used to describe the artifacts published by this module.

If this container is not present, it is assumed that the module has one artifact, with the same name as the module, and published in all module configurations.

Thus if you have a module which publishes no artifacts (a sort of virtual module, made only to integrate several other modules as a whole), you have to include a publications element with no `artifact` sub element.

== Attributes

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|defaultconf|comma separated list of public configurations in which artifacts are published by default (when no specific configurations are set on the artifact element).
`$$*$$` wildcard can be used to designate all public configurations of this module. (*__since 2.0__*)|No, defaults to `$$*$$`
|=======

== Child elements

[options="header",cols="20%,60%,20%"]
|=======
|Element|Description|Cardinality
|link:../ivyfile/artifact{outfilesuffix}[artifact]|declares a published artifact for this module|0..n
|=======
