////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

*Tag:* repository *Parent:* link:../ivyfile/info{outfilesuffix}[info]

Gives information about a public repository where the module can be found. This information is given as an indication, repositories being able to be down over time.

== Attributes

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|name|the name of the repository. Try to respect spelling for common repositories (ibiblio, ivyrep, ...)|Yes
|url|an URL pointing to the repository.|Yes
|pattern|an Ivy pattern to find modules on this repository|No, but it's recommended to indicate it.
|ivys|`true` if Ivy file can be found on this repository|No, defaults to `false`.
|artifacts|`true` if module artifacts can be found on this repository|No, defaults to `false`.
|=======
