////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= fromsystem / tosystem

*Tag:* fromsystem / tosystem

[ivysettings.namespaces.namespace.fromsystem]#Defines a one way translation rule, i.e. a translation from system namespace to the defined namespace or vice versa.#

== Child elements


[options="header"]
|=======
|Element|Description|Cardinality
|link:../../settings/namespace/src{outfilesuffix}[src]|defines a source name which can be accepted|1..n
|link:../../settings/namespace/dest{outfilesuffix}[dest]|defines the translation to apply when a name is accepted by an src pattern|1
|=======
