
Constructs an ant path consisting of artifacts in ivy cache (or origin location with depending on useOrigin setting) for a resolved module configuration.

This is a link:../use/postresolvetask.html[post resolve task], with all the behaviour and attributes common to all post resolve tasks.

If you want to make your build more independent from Ivy, you could consider using the link:../use/retrieve.html[retrieve task]. Once the artifacts are properly retrieved, you can use standard Ant path creation which makes Ivy not necessary any more.

Built path is registered in ant with a given id, and can thus be used like any other ant path using refid.
  

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|pathid|the id to reference the built path|Yes
|conf|a comma separated list of the configurations to put in the created path|No. Defaults to the configurations resolved by the last resolve call, or * if no resolve was explicitly called
|type|comma separated list of artifact types to accept in the path, * for all (*__since 1.2__*)|No. Defaults to *
|settingsRef|*__(since 2.0)__* A reference to the ivy settings that must be used by this task|No, 'ivy.instance' is taken by default.
|=======



== Examples


[source]
----

<cachepath pathid="default.classpath" conf="default" />

----

Construct an ant path composed of all artifacts being part of the default configuration obtained through the last resolve call.


'''



[source]
----

<cachepath pathid="default.classpath" conf="default" useOrigin="true" />

----

Same as before but will use the original location for local artifacts, and the cache location for other artifacts.


'''



[source]
----

<ivy:cachepath organisation="emma" module="emma" revision="2.0.4217" inline="true" conf="ant" pathid="emma.classpath"/>
<taskdef resource="emma_ant.properties" classpathref="emma.classpath" /> 

----

Resolves the emma module in version 2.0.4217, constructs an ant path with the corresponding artifacts, and then define the emma tasks using this path.