
Display dependency updates on the console. This task can also show transitive dependencies updates and detect missing or new dependencies if you update dependencies.

This is a link:../use/postresolvetask.html[post resolve task], with all the behaviour and attributes common to all post resolve tasks.

Please prefer the use of retrieve + standard ant path creation, which make your build more independent from ivy (once artifacts are properly retrieved, ivy is not required any more).


== Attributes



[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|revisionToCheck|target revision to check|No. Defaults to 'latest.integration'
|download|specify if artifact should be downloaded when new updates are found|No. Defaults to 'false'
|checkIfChanged|When set to true, the resolve will compare the result with the last resolution done on this module, with those configurations in order to define the property ivy.deps.changed.  Put it to false may provides slightly better performance.|No, default to 'false'
|showTransitive|set to true if you want to see potential updates on transitive dependencies|No. Defaults to 'false'
|=======



== Example

Suppose we have two dependencies one called __mydep__ in revision 1.0 and one called __myotherdependency__ in revision 2.0.
__mydep__ has a transitive dependency on __mytransitivedependency__ in revision 2.2.

Then:

[source]
----

<checkdepsupdate />

----

will display the following updates in the console:

[source]
----

Dependencies updates available :
   mycompany#mydep    1.0 -> 2.0
   mycompany#myotherdependency  2.0 -> 2.2

----

Same example with transitive dependencies :

[source]
----

<checkdepsupdate showTransitive="true" />

----

will display the following updates in the console:

[source]
----

Dependencies updates available :
   mycompany#mydep    1.0 -> 2.0
   mycompany#myotherdependency  2.0 -> 2.2
   mycompany##mytransitivedependency (transitive)    2.2 -> 2.4

----

