////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= Bintray resolver

[]
|=======
|Tag|bintray
|Handle latest|yes, at least if the repository server is apache based
|Handle publish|no
|=======

[*__since 2.4__*]

[ivysettings.resolvers.bintray]#This resolver uses Bintray DaaS (Distribution as a Service) platform to retrieve artifacts.#


== Attributes


[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|subject|Bintray username of a repository owner.|No, defaults to Bintray
|repo|User's repository name.|No, defaults to JCenter
|=======



== Examples


[source]
----

<bintray/>

----

A default, defines a link:https://bintray.com/bintray/jcenter[JCenter] bintray resolver.
In most circumstances you won't need any other resolvers as JCenter is already a super-set of many other repositories, including Maven Central.


'''



[source, xml]
----

<bintray subject="dsowerby" repo="maven"/>
<bintray subject="igelgrun" repo="batrak"/>

----

Defines two resolvers to use a link:https://bintray.com/dsowerby/maven[repository] "maven" of user "dsowerby" (https://dl.bintray.com/dsowerby/maven/)
and link:https://bintray.com/igelgrun/batrak[repository] "batrak" of user "igelgrun" (https://dl.bintray.com/igelgrun/batrak/).
