////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= Ibiblio resolver

[]
|=======
|Tag|ibiblio
|Handle latest|yes, at least if the repository server is apache based
|Handle publish|no
|=======


[ivysettings.resolvers.ibiblio]#This resolver usually uses ibiblio to find artifacts.#

(*__since 1.3__*) Using the `m2compatible` attribute, you can benefit from Maven 2 repository compatibility (convert dots in organisation into slashes, search for POMs, use transitive dependencies of POMs). This setting also affects the default place where the resolver looks for its artifacts to point to the Maven 2 repository. So setting this attribute to `true` is sufficient to use Maven 2 ibiblio repository.

(*__since 1.4__*) When using the `m2compatible` flag, you can disable the use of POMs by setting the usepoms flag to `false`. It is then roughly equivalent to a URL resolver configured like this:

[source, xml]
----

<url name="test" m2compatible="true">
  <artifact pattern="https://repo1.maven.org/maven2/[organisation]/[module]/[revision]/[artifact]-[revision].[ext]"/>
</url>

----

(*__since 2.0__*) When used in `m2compatible` mode with the default pattern, this resolver uses `maven-metadata.xml` files (if present) to list the revisions available on the repository. This is especially useful when using a Maven specific proxy, which does not serve directory listing. This can be disabled by using the `useMavenMetadata` flag.

*Limitation*: in `m2compatible` mode, this resolver is not able list available organizations. It means some features like link:../use/repreport{outfilesuffix}[repreport] are not available.


== Attributes

This resolver shares the link:../settings/resolvers{outfilesuffix}#common[common attributes] of standard resolvers.

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|root|the root of the artifact repository.|No, defaults to ${ivy.ibiblio.default.artifact.root}
|pattern|a pattern describing the layout of the artifact repository.|No, defaults to ${ivy.ibiblio.default.artifact.pattern}
|m2compatible|True if this resolver should be Maven 2 compatible, false otherwise (*__since 1.3__*)|No, defaults to false
|usepoms|True if this resolver should use Maven POMs when it is already in m2compatible mode, false otherwise (*__since 1.4__*)|No, defaults to true
|useMavenMetadata|True if this resolver should use maven-metadata.xml files to list available revisions, false to use directory listing (*__since 2.0__*)|No, defaults to true
|=======



== Examples


[source, xml]
----

<ibiblio name="maven2" m2compatible="true"/>

----

Defines a resolver called `maven2` using the Maven 2 public repository to find module metadata (using Maven 2 POMs) and artifacts.


'''


[source, xml]
----

<ibiblio name="maven" m2compatible="true" usepoms="false"/>

----

Same as above, but doesn't use POMs, only artifacts.
