////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= IvyRep resolver

[]
|=======
|Tag|ivyrep
|Handle latest|yes, at least if the repository server is apache based
|Handle publish|no
|=======

[ivysettings.resolvers.ivyrep]#This resolver usually uses an URL based repository usually similar in structure to the, now defunct, `http://ivyrep.jayasoft.org/` repo, to find Ivy files, and ibiblio to find artifacts.# It can also be configured to use other similar repositories.


[NOTE]
====

Since ivyrep is not maintained anymore, the ivyroot attribute is mandatory, and the use of this resolver is not recommended (we recommend using link:../resolver/url{outfilesuffix}[url resolver] as replacement in most cases).

====



== Attributes

This resolver shares the link:../settings/resolvers{outfilesuffix}#common[common attributes] of standard resolvers.

[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|ivyroot|the root of the Ivy repository.|Yes, but may be provided through ${ivy.ivyrep.default.ivy.root} (*__since 2.0__*)
|ivypattern|a pattern describing the layout of the Ivy repository.|No, defaults to ${ivy.ivyrep.default.ivy.pattern}
|artroot|the root of the artifacts repository.|No, defaults to ${ivy.ivyrep.default.artifact.root}
|artpattern|a pattern describing the layout of the artifacts repository.|No, defaults to ${ivy.ivyrep.default.artifact pattern}
|=======


== Examples


[source, xml]
----

<ivyrep name="ivyrep" ivyroot="http://ivyrep.mycompany.com"/>

----

Looks for Ivy files in an ivyrep like web site located at `http://ivyrep.mycompany.com`.
