////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= settings

*Tag:* settings

[ivysettings.settings]#Configures some important Ivy behaviour: default resolver, latest strategy, conflict manager and some others.#

The default resolver is used whenever nothing else is configured in the modules section of the settings file. It should give the name of a dependency resolver defined in the link:../settings/resolvers{outfilesuffix}[resolvers] section of the settings file.

The default latest strategy and conflict manager can also be configured here.

_validate_ indicates if Ivy files should generally be validated against the Ivy XSD or not. This setting is only a default value, and can be overridden:

    1. in Ant tasks
    2. in resolvers

So if there is a setting in the resolver, it always wins against all other settings.


== Attributes


[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|defaultResolver|the name of the default resolver to use|No, but all modules should be configured in the modules section if not provided
|defaultLatestStrategy|the name of the default latest strategy to use|No, defaults to latest-revision
|defaultConflictManager|the name of the default conflict manager to use|No, defaults to latest-revision
|defaultBranch|the default branch to use for all modules, except if they have a link:../settings/module{outfilesuffix}[module specific branch setting]. (*__since 1.4__*)|No, defaults to no default branch
|defaultResolveMode|the default link:../use/resolve{outfilesuffix}[resolve mode] to use for all modules, except if they have a link:../settings/module{outfilesuffix}[module specific resolve mode setting]. (*__since 2.0__*)|No, defaults to 'default'
|[[circularDependencyStrategy]]circularDependencyStrategy|the name of the link:../concept{outfilesuffix}#circular[circular dependency strategy] to use (*__since 1.4__*)|No, defaults to warn
|validate|Indicates if Ivy files should be validated against ivy.xsd or not.|No, defaults to true
|useRemoteConfig|true to configure ivyrep and ibiblio resolver from a remote settings file (updated with changes in those repository structure if any) (*__since 1.2__*)|No, defaults to false
|httpRequestMethod|specifies the HTTP method to use to retrieve information about an URL. Possible values are 'GET' and 'HEAD'. This setting can be used to solve problems with firewalls and proxies. (*__since 2.0__*)|No, defaults to 'HEAD'
|[line-through]#defaultCache#|a path to a directory to use as default basedir for both resolution and repository cache(s). +
__Deprecated, we recommend using defaultCacheDir on the link:../settings/caches{outfilesuffix}[caches] tag instead__|No, defaults to .ivy2/cache in user home
|[line-through]#checkUpToDate#|Indicates if date should be checked before retrieving artifacts from cache. +
__Deprecated, we recommend using overwriteMode on the link:../use/retrieve{outfilesuffix}[retrieve] task instead__|No, defaults to true
|[line-through]#cacheIvyPattern#|a pattern to indicate where Ivy files should be put in cache. +
__Deprecated, we recommend using ivyPattern on the link:../settings/caches{outfilesuffix}[caches] tag instead__|No, defaults to [organisation]/[module]/ivy-[revision].xml
|[line-through]#cacheArtifactPattern#|a pattern to indicate where artifact files should be put in cache. +
__Deprecated, we recommend using artifactPattern on the link:../settings/caches{outfilesuffix}[caches] tag instead__|No, defaults to [organisation]/[module]/[type]s/[artifact]-[revision].[ext]
|=======
