////
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.
////

= typedef

*Tag:* typedef

[ivysettings.typedef]#Defines a new type in Ivy. Useful to define new dependency resolvers, in particular, but also latest strategies.#
See link:../extend{outfilesuffix}[how to write and plug your own dependency resolver] for details.

== Attributes


[options="header",cols="15%,50%,35%"]
|=======
|Attribute|Description|Required
|name|the name of the type to define. This name is then used as an xml tag.|Yes
|classname|the fully qualified class name of the type to define.|Yes
|=======
