<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>
<xsl:template match="/ivy-report">
  <xsl:text>/* * directed graph dot input file. * * generated by ivy report */
            digraph G {</xsl:text>
  <xsl:for-each select="dependencies/module">
   	<xsl:text>"</xsl:text><xsl:value-of select="@name"/><xsl:text>"</xsl:text>
  </xsl:for-each>
  <xsl:for-each select="dependencies/module/revision[not(@evicted)]/caller[@organisation!='caller']">
   	<xsl:text>"</xsl:text><xsl:value-of select="@name"/><xsl:text>" -&gt; "</xsl:text><xsl:value-of select="../../@name"/><xsl:text>";</xsl:text>
  </xsl:for-each>
  <xsl:text>}</xsl:text>
</xsl:template>
</xsl:stylesheet>
